apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ay0f6o5nm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ay0f6o5nm-go 
  name: ay0f6o5nm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ay0f6o5nm-go 
